### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by Kushal-2002** [vasu-1/CalcHub#22]
### Calculator Functions

The objective of this JavaScript project is to wire up a very basic JavaScript BMI Calculator.
Key concepts covered :-
1.) document.querySelector()
2.) event listeners
3.) parseInt()
4.) toFixed()
5.) innerHTML

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by SayedTabish72** [comment]
## 🙋‍♂️𝗛𝗶 [Kushal Mukherjee](https://github.com/Kushal-2002),
This is [Sayed Tabish](https://github.com/SayedTabish72). I'm participant of **GirlScript Summer Of Code 2022.**  And also I'm Experienced Freelance Web Developer with a demonstrated history of working in the internet industry. Strong engineering professional with a Bachelor of Technology - BTech focused in Information Technology from Dr. A.P.J. Abdul Kalam Technical University. 

👨‍💻And It's very nice to contribute and work for **[CalcHub](https://github.com/vasu-1/CalcHub)** and
 **BMI Calculator #22** I am interested to work on this issue And also I want to work on such a project that. because I have already worked on similar kind of projects.
**Like:**
![Proudly created by @Sayed tabish](https://user-images.githubusercontent.com/93794214/145717508-ef4069f1-e5e3-4b72-8633-f51f618360b9.png)
![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ,   ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) , ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E)
It will give me a stage to apply my knowledge. building innovative product and put my technical skill to use. plz assign me for the contribution. **I'd love if you assign me for the contribution😊.**
