### ISSUE TITLE
Temperature Calculator

### ISSUE THREAD

**Issue by devgirlcodes** [vasu-1/CalcHub#29]
### Calculator Functions

The calculator will convert temperature from one unit to the other. It will have options for conversion between any two of the following units:

1. Celsius
2. Kelvin
3. Fahrenheit

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

**Comment by SayedTabish72** [comment]
## 🙋‍♂️𝗛𝗶 [Akshita Singh](https://github.com/devgirlcodes)  
This is [Sayed Tabish](https://github.com/SayedTabish72). I'm participant of GirlScript Summer Of Code 2022.  And also I'm Experienced Freelance Web Developer with a demonstrated history of working in the internet industry. Strong engineering professional with a Bachelor of Technology - BTech focused in Information Technology from Dr. A.P.J. Abdul Kalam Technical University. 

👨‍💻And It's very nice to contribute and work for [CalcHub](https://github.com/vasu-1/CalcHub) I am interested to work on this issue And also I want to work on such a project that. because I have already worked on similar kind of calculations and mathematical projects.
**Link:** [JavascriptAppCalculator.github.io](https://github.com/SayedTabish72/JavascriptAppCalculator.github.io)
![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ,   ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) , ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E)
It will give me a stage to apply my knowledge. building innovative product and put my technical skill to use.
